### ISSUE TITLE
请问该bot如何使用

### ISSUE THREAD

**Issue by xianyujunshigeCDD** [SK-415/bilibili-dd-bot#1]
dalao，请问这个bot需要怎么使用，我点开一直闪退

**Comment by SK-415** [comment]
刚刚在 readme 更新了一个简单说明，希望对你有帮助

**Comment by xianyujunshigeCDD** [comment]
> 刚刚在readme更新了一个简单说明，希望对你有帮助

dalao，我按照你的说明操作之后显示ModuleNotFoundError: No module named 'config'，使用pip install config安装后显示AttributeError: module 'config' has no attribute 'DEBUG'，请问如何处理

**Comment by xianyujunshigeCDD** [comment]
这是具体操作过程
C:\Users\DELL\Desktop\dd-bot-1.2.1>python bot.py
ujson module not found, using json
Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    import config
ModuleNotFoundError: No module named 'config'

C:\Users\DELL\Desktop\dd-bot-1.2.1>pip install config
Requirement already satisfied: config in e:\gongju\ad3\lib\site-packages (0.5.0.post0)

C:\Users\DELL\Desktop\dd-bot-1.2.1>python bot.py
ujson module not found, using json
Traceback (most recent call last):
  File "bot.py", line 11, in <module>
    nonebot.init(config)
  File "C:\Users\DELL\Desktop\dd-bot-1.2.1\nonebot\__init__.py", line 71, in init
    _bot = NoneBot(config_object)
  File "C:\Users\DELL\Desktop\dd-bot-1.2.1\nonebot\__init__.py", line 29, in __init__
    self.asgi.debug = self.config.DEBUG
AttributeError: module 'config' has no attribute 'DEBUG'

**Comment by SK-415** [comment]
这个是我的失误, 我忘记写了, 请把根目录中的 `config.example.py` 文件重命名为 `config.py`, 然后再尝试运行 `python bot.py`.

**Comment by xianyujunshigeCDD** [comment]
> 这个是我的失误，我忘记写了，请把根目录中的`config.example.py`文件重命名为`config.py`，然后再尝试运行`python bot.py`。
请问在启动之后如何进行配置

**Comment by xianyujunshigeCDD** [comment]
> 这个是我的失误，我忘记写了，请把根目录中的`config.example.py`文件重命名为`config.py`，然后再尝试运行`python bot.py`。
显示后就没反应了
C:\Users\DELL\Desktop\dd-bot-1.2.1>python bot.py
ujson module not found, using json
[2020-10-01 21:49:58,970 nonebot] INFO: Succeeded to import "nonebot.plugins.base"
[2020-10-01 21:49:58,971 nonebot] INFO: Succeeded to import "help"
[2020-10-01 21:49:58,973 nonebot] INFO: Succeeded to import "plugins.dd_bot.auto_agree"
[2020-10-01 21:49:59,086 nonebot] INFO: Succeeded to import "plugins.dd_bot.config_manager"
[2020-10-01 21:49:59,115 nonebot] INFO: Succeeded to import "plugins.dd_bot.dynamic"
[2020-10-01 21:49:59,116 nonebot] INFO: Succeeded to import "plugins.dd_bot.live_reminder"
[2020-10-01 21:49:59,116 nonebot] INFO: Succeeded to import "plugins.dd_bot.utils"
[2020-10-01 21:49:59,117 nonebot] INFO: Running on 0.0.0.0:8080
Running on https://0.0.0.0:8080 (CTRL + C to quit)
[2020-10-01 21:49:59,118] ASGI Framework Lifespan error, continuing without Lifespan support
[2020-10-01 21:49:59,120 nonebot] INFO: Scheduler started

**Comment by SK-415** [comment]
向你的机器人发送 `帮助` 可以获取到所有的口令名称. 不过有些比较抽象的口令我没有写具体的说明，还请自己琢磨一下. 我现在处于赶作业赶疯掉的状态, 等国庆结束了我会更新一份详细的说明文档

**Comment by Polyisoprene** [comment]
怎么配置监控的主播和发布信息的群聊？？？

**Comment by SK-415** [comment]
> 怎么配置监控的主播和发布信息的群聊？？？

向机器人发送 `帮助` 可以查看所有命令, 在对应群内@机器人使用即可

**Comment by Polyisoprene** [comment]
但是，bot和go-cqhttp都运行后，虽然go-cqhttp的运行界面能够显示群聊里别人发的消息，但是发帮助什么都没有发生

**Comment by SK-415** [comment]
- 在群里发的任何指令前都要@机器人
- go-cqhttp 新登录的账号会被tx风控，具体表现为群里发不出消息但是私聊可以，放服务器上挂两天就好了

**Comment by Polyisoprene** [comment]
可是私聊发帮助也没有回应

**Comment by SK-415** [comment]
> 可是私聊发帮助也没有回应

结合你之前的描述，我唯一能想到的情况，就是你的 bot 根本没能连上 go-cqhttp, 请参考 `README.md` 检查自己的配置文件.
